# Generated by Django 5.2.1 on 2025-05-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nargile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('bowl_type', models.CharField(max_length=20, null=True)),
                ('bowl_material', models.CharField(max_length=20, null=True)),
                ('tobacco', models.CharField(max_length=20, null=True)),
                ('years_of_usage', models.CharField(max_length=20, null=True)),
                ('flask_volume', models.IntegerField(null=True)),
            ],
        ),
    ]
