# Generated by Django 5.2.1 on 2025-05-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nargile',
            name='bowl_material',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nargile',
            name='bowl_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nargile',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nargile',
            name='tobacco',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nargile',
            name='years_of_usage',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
